// <auto-generated />
namespace TravelTripProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addlikestatustoblog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlikestatustoblog));
        
        string IMigrationMetadata.Id
        {
            get { return "202209291015488_add-likestatus-to-blog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
